### ISSUE TITLE
Implement Matrix chat notifications for specific pipelines and those that fail

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/zuul#5]
As a user of Zuul CI, I want to receive notifications through a Matrix chat when my pipeline encounters failures.

Several solutions/ideas have already been discussed in SCS meetings and chats:

a) Zuul Mqtt reporter -> Mqtt/Matrix daemon -> Matrix
- Mqtt/Matrix daemon consumes MQTT reports from Zuul and then ct
- Pros: 
  - The Zuul MQTT reporter offers 'complete build information in a single response', see reporter message example [here](https://zuul-ci.org/docs/zuul/latest/drivers/mqtt.html)
  - Something similar has been implemented by Zuul devs, hence this solution is somehow recommended by the Zuul community, see [here](https://matrix.to/#/!yuuvjJSOEGSfTzxOjK:opendev.org/$vLkNSMhxxFOu-iQ_4A1w_4MtA4nBTX1o2VnPEPMV-rQ?via=matrix.org&via=opendev.org&via=acmegating.com)
- Cons:
  - It seems that Mqtt/Matrix daemon implementation does not exist and should be created

b) Zuul Statsd reporter -> Statsd receiver -> Prometheus [statsd_exporter](https://github.com/prometheus/statsd_exporter) -> Prometheus -> Prometheus Alertmanager -> [matrix-alertmanager-receiver](https://git.sr.ht/~fnux/matrix-alertmanager-receiver) -> Matrix
-  Statsd receiver consumes stated metrics, then statsd_exporter [translates](https://softwarefactory-project.io/r/c/software-factory/sf-operator/+/29482/24/controllers/static/zuul/statsd_mapping.yaml) these metrics to the Prometheus form of metrics, then Prometheus pulls and stores metrics and finally, if any alert condition hits, Prometheus pushes it to the AlertManager which sends the report to the [matrix-alertmanager-receiver](https://git.sr.ht/~fnux/matrix-alertmanager-receiver) and the receiver relays reports to the Matrix chat
- Pros: 
  - All needed components exist as open-source projects and could be used
  - According to the Zulu community chat, a similar idea has been considered by another team, but not implemented yet nor evaluated further, see [here](https://matrix.to/#/!yuuvjJSOEGSfTzxOjK:opendev.org/$J0Cx29tE87DjceqPAGJSOO6-YwGWr8rXy6GlRbK9o7M?via=matrix.org&via=opendev.org&via=acmegating.com)
- Cons: 
  - The Prometheus infrastructure does not exist yet in the SCS env.
  -  The Prometheus alermanager does not support/have [matrix chat receiver](https://prometheus.io/docs/alerting/latest/configuration/#receiver-integration-settings), but there are some projects that cover also this missing piece, e.g.:  [matrix-alertmanager-receiver](https://git.sr.ht/~fnux/matrix-alertmanager-receiver) 
  - Mapping from stastd to Prometheus metrics could be also tricky, luckily there is something available: https://softwarefactory-project.io/r/c/software-factory/sf-operator/+/29482/24/controllers/static/zuul/statsd_mapping.yaml
  - A lot of components are involved and need to be configured   
  - Could be tricky to collect all relevant information from metrics, and compose a nice report message in the Matrix chat

**Comment by bitkeks** [comment]
Closing this, because @matofeder finished the proposed implementation and there was no more activity since Oct. 2023.
